version: '3.7'

services:

    rancher:
        image: 'rancher/rancher:${RANCHER_IMAGE_VERSION}'
        container_name: rancher
        networks:
            - backend
        hostname: rancher
        restart: unless-stopped
        ports:
            - '8080:80'
        entrypoint: bash -c "tini -- rancher --http-listen-port=8080"

    certbot:
        depends_on:
            - proxy
        image: certbot/certbot
        container_name: certbot
        networks:
            - backend
        volumes:
            - 'certbot-etc:${LETSENCRYPT_CONF_PREFIX}'
            - '/tmp/acme-challenge:/tmp/acme-challenge'                        
        restart: unless-stopped        
        environment:
            TZ: '${LOCAL_TIMEZONE}'
        entrypoint: /bin/sh -c "certbot certonly --webroot --webroot-path /tmp/acme-challenge --rsa-key-size 4096 --non-interactive --agree-tos --no-eff-email --force-renewal --email ${LETSENCRYPT_EMAIL} -d ${DOMAIN_NAME} -d www.${DOMAIN_NAME}; 
            trap exit TERM; while :; do certbot renew --dry-run; sleep 12h & wait $${!}; done;"

    proxy:
        depends_on:
            - rancher
        image: nginx:stable
        container_name: proxy
        networks:
            - backend
            - frontend
        volumes:
            - type: bind
              source: ./proxy/nginx.conf
              target: '${PROXY_PREFIX}/nginx.conf'
            - type: bind
              source: ./proxy/templates/proxy.conf.template
              target: '${PROXY_PREFIX}/templates/default.conf.template'
            #- type: bind
            #  source: ./proxy/ssl-option/options-ssl-nginx.conf
            #  target: '${LETSENCRYPT_CONF_PREFIX}/options-ssl-nginx.conf'
            - type: bind
              source: ./ssl-proxyconf.sh
              target: '/tmp/ssl-proxyconf.sh'
            - 'certbot-etc:${LETSENCRYPT_CONF_PREFIX}'
            - '/tmp/acme-challenge:/tmp/acme-challenge'
        hostname: proxy
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        links:
            - rancher
        environment:
            NGINX_HOST: ${DOMAIN_NAME}
            NGINX_PORT: 80
            TZ: '${LOCAL_TIMEZONE}'
        command: bash -c "/docker-entrypoint.sh nginx -v; sh /tmp/ssl-proxyconf.sh '${DOMAIN_NAME}' '${LETSENCRYPT_CONF_PREFIX}' '${PROXY_PREFIX}'"

networks:
    backend: null
    frontend: null

volumes:
    certbot-etc:
        name: certbot-etc
